# Test-only HTTP endpoints for the Drift suite.
#
# Drift needs the database to hold exactly the rows one operation's request
# needs, and nothing else, so drift/pact_broker.lua calls these two routes
# around every operation:
#
#   POST /test/setup/{operationId} — seeds the DB for that one operation via
#     PactBroker::Test::TestDataBuilder, and answers with the values the
#     seeding *generated* rather than chose (UUID primary keys, the
#     pact-version SHA), since drift.yaml can't hardcode those.
#   POST /test/reset — truncates the DB, so operations don't see each other's
#     state.
#
# Mounted as Rack middleware in front of the real app rather than as a
# separate server, so Drift only has one base URL to talk to.

require "json"
require "securerandom"
require "pact_broker/test/test_data_builder"
require "pact_broker/db/table_dependency_calculator"

module PactBroker
  module Drift
    # Names chosen by the seeding below, not generated by it — safe to
    # hardcode directly in drift.yaml path/body parameters. Kept identical to
    # the `fixtures` module in pact_broker-rs's tests/drift.rs so the same
    # drift.yaml drives both implementations.
    CONSUMER = "Foo"
    PROVIDER = "Bar"
    CONSUMER_VERSION = "1.0.0"
    PROVIDER_VERSION = "4.5.6"
    BRANCH = "main"
    TAG = "prod"
    LABEL = "keep"
    ENVIRONMENT = "test"

    class TestState
      SETUP = %r{\A/test/setup/(.+)\z}
      RESET = "/test/reset"

      def initialize(app, database = nil)
        @app = app
        @database = database
      end

      def call(env)
        return @app.call(env) unless env["REQUEST_METHOD"] == "POST"

        case env["PATH_INFO"]
        when RESET
          truncate
          json(200, message: "reset")
        when SETUP
          setup($1)
        else
          @app.call(env)
        end
      end

      private

      def setup(operation_id)
        context = seed(operation_id)
        if context.nil?
          # A 400 rather than a silent no-op: an operation key in drift.yaml
          # with no branch below would otherwise run against an empty
          # database and fail somewhere far less obvious.
          json(400, message: "unknown operation: #{operation_id}")
        else
          json(200, context)
        end
      rescue StandardError => e
        json(500, message: "#{e.class}: #{e.message}", backtrace: e.backtrace&.first(5))
      end

      # Resolved on first use, not at construction: PactBroker::App sets up
      # PactBroker::DB.connection while it boots, and this middleware is
      # wrapped around the app in the same breath.
      def database
        @database ||= PactBroker::DB.connection
      end

      def truncate
        PactBroker::DB::TableDependencyCalculator.call(database).each do | table_name |
          database[table_name].delete if database.table_exists?(table_name)
        end
      end

      def json(status, body)
        [status, { "content-type" => "application/json" }, [body.to_json]]
      end

      # Everything the seeding generated rather than chose. drift.yaml reads
      # these back out through ${functions:...}.
      def context_for(builder)
        context = {}
        context["consumerName"] = builder.consumer.name if builder.consumer
        context["providerName"] = builder.provider.name if builder.provider
        context["consumerVersionNumber"] = builder.consumer_version.number if builder.consumer_version
        context["providerVersionNumber"] = builder.provider_version.number if builder.provider_version
        context["pactVersionSha"] = builder.pact.pact_version_sha if builder.pact
        if builder.environment
          context["environmentName"] = builder.environment.name
          context["environmentUuid"] = builder.environment.uuid
        end
        context["deployedVersionUuid"] = builder.deployed_version.uuid if builder.deployed_version
        context["releasedVersionUuid"] = builder.released_version.uuid if builder.released_version
        context["webhookUuid"] = builder.webhook.uuid if builder.webhook
        context
      end

      # Seeds the database for a single Drift operation. Returns nil for an
      # unrecognised operation_id; otherwise the generated identifiers the
      # operation's request needs, per #context_for.
      #
      # The branches below are a direct port of `seed_state` in
      # pact_broker-rs's tests/drift.rs, deliberately kept in the same order
      # and with the same groupings so the two can be diffed against each
      # other when drift.yaml changes.
      #
      # rubocop: disable Metrics/CyclomaticComplexity, Metrics/MethodLength
      def seed(operation_id)
        b = PactBroker::Test::TestDataBuilder.new

        case operation_id
        when "getIndex_Success", "dependencies", "heartbeat", "get_relationships",
             "metrics_handler"
          # No state required.

        when "list_pacticipants", "get_pacticipant", "list_versions",
             "list_branches", "get_branch", "list_branch_versions", "list_labels", "get_tag", "list_versions_for_tag", "get_latest_version", "get_latest_version_for_tag",
             "can_i_deploy_by_tag_to_tag", "get_pacticipants_by_label"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION, branch: BRANCH)
          b.create_consumer_version_tag(TAG)
          b.create_label(LABEL)

        # The environment is part of the path, so it has to exist for the
        # route to resolve at all, not just for the answer to be meaningful.
        when "can_i_deploy_by_branch_to_environment"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION, branch: BRANCH)
          b.create_environment(ENVIRONMENT, production: false)

        when "list_environments", "get_environment", "list_currently_deployed_versions",
             "list_currently_supported_versions"
          b.create_environment(ENVIRONMENT, production: false)

        when "get_deployed_version"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_environment(ENVIRONMENT, production: false)
          b.create_deployed_version_for_consumer_version(currently_deployed: true, environment_name: ENVIRONMENT)

        when "get_released_version"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_environment(ENVIRONMENT, production: false)
          b.create_released_version_for_consumer_version(currently_supported: true, environment_name: ENVIRONMENT)

        when "record_deployment_for_version", "record_release_for_version",
             "record_undeployment", "end_support"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_environment(ENVIRONMENT, production: false)
          if operation_id == "record_undeployment"
            b.create_deployed_version_for_consumer_version(currently_deployed: true, environment_name: ENVIRONMENT)
          end
          if operation_id == "end_support"
            b.create_released_version_for_consumer_version(currently_supported: true, environment_name: ENVIRONMENT)
          end

        when "create_pacticipant", "create_environment_op"
          # Creating a fresh top-level resource: nothing to seed, and
          # /test/reset between operations guarantees a clean slate.

        # Also creating fresh resources, but nested under a pacticipant that
        # has to already exist or the route 404s before the body is read.
        when "put_pacticipant", "put_version", "create_version", "create_branch", "create_tag",
             "create_label"
          b.create_consumer(CONSUMER)
          # PUT answers 201 for a version it had to create, so the version
          # has to pre-exist for the documented 200 to be the right answer.
          b.create_consumer_version(CONSUMER_VERSION) if operation_id == "put_version"

        when "delete_pacticipant", "patch_pacticipant", "delete_branch", "delete_label",
             "delete_tag", "delete_version", "delete_environment"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION, branch: BRANCH)
          b.create_consumer_version_tag(TAG)
          b.create_label(LABEL)
          b.create_environment(ENVIRONMENT, production: false) if operation_id == "delete_environment"

        when "get_version", "list_deployed_versions_for_version_and_environment"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_environment(ENVIRONMENT, production: false)

        when "publish_pact", "publish_contracts"
          # The consumer/provider are created implicitly by the publish
          # itself; nothing to seed.

        when "fetch_pact", "fetch_latest_pact", "fetch_latest_tagged_pact", "latest_pact_badge",
             "latest_untagged_pact_badge", "latest_tagged_pact_badge", "get_latest_pacts",
             "fetch_provider_pacts", "fetch_provider_pacts_for_tag", "latest_provider_pacts",
             "latest_tagged_provider_pacts", "fetch_tagged_pact_versions", "get_pact_versions",
             "fetch_pact_webhooks_status", "list_provider_states", "pacts_for_verification",
             "fetch_provider_pacts_for_main_branch", "fetch_latest_provider_pacts_for_main_branch",
             "fetch_provider_pacts_for_named_branch", "fetch_latest_provider_pacts_for_named_branch",
             "fetch_pact_versions_for_main_branch", "fetch_latest_pact_versions_for_main_branch",
             "fetch_pact_versions_for_named_branch", "fetch_latest_pact_versions_for_named_branch",
             "fetch_latest_branch_pact", "list_triggered_webhooks_for_pact", "matrix_tag_badge",
             "fetch_matrix", "fetch_matrix_for_pair", "can_i_deploy", "can_i_merge_badge_route",
             "can_i_deploy_by_tag_to_tag_badge", "can_i_deploy_by_branch_to_environment_badge",
             "get_dashboard", "get_dashboard_for_pair", "list_integrations", "get_integration",
             "list_groups"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION, branch: BRANCH)
          b.create_consumer_version_tag(TAG)
          b.create_provider(PROVIDER)
          b.create_pact

        # These three need *two* pacts whose content differs, and no tag on
        # either: "previous distinct" has nothing to point back at from a
        # single publication, and "latest untagged" excludes tagged versions.
        when "fetch_diff_previous_distinct", "fetch_previous_distinct_pact_version",
             "fetch_latest_untagged_pact"
          b.create_consumer(CONSUMER)
          b.create_provider(PROVIDER)
          b.create_consumer_version("0.9.0")
          b.create_pact(json_content: {
            "consumer" => { "name" => CONSUMER },
            "provider" => { "name" => PROVIDER },
            "interactions" => []
          }.to_json)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_pact(json_content: {
            "consumer" => { "name" => CONSUMER },
            "provider" => { "name" => PROVIDER },
            "interactions" => [{ "description" => "a request", "response" => { "status" => 200 } }]
          }.to_json)

        when "get_latest_verification", "get_latest_verification_for_latest_pact",
             "get_latest_verification_for_latest_tagged_pact", "get_latest_verification_for_publication",
             "get_verification", "delete_verification", "list_triggered_webhooks_for_verification",
             "get_latest_verifications_for_consumer_version"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION, branch: BRANCH)
          b.create_consumer_version_tag(TAG)
          b.create_provider(PROVIDER)
          b.create_pact
          b.create_verification(provider_version: PROVIDER_VERSION, success: true)

        when "publish_verification"
          b.create_consumer(CONSUMER)
          b.create_consumer_version(CONSUMER_VERSION)
          b.create_provider(PROVIDER)
          b.create_pact

        when "list_webhooks", "list_consumer_webhooks", "list_provider_webhooks",
             "list_pact_webhooks", "get_webhook", "update_webhook", "delete_webhook",
             "execute_saved_webhook"
          b.create_consumer(CONSUMER)
          b.create_provider(PROVIDER)
          b.create_webhook(event_names: ["contract_published"])

        when "create_webhook", "create_consumer_scoped_webhook", "create_provider_scoped_webhook",
             "create_pact_scoped_webhook", "execute_unsaved_webhook"
          b.create_consumer(CONSUMER)
          b.create_provider(PROVIDER)

        when "test_error_get", "test_error_post"
          # No state required.

        else
          return nil
        end

        context_for(b)
      end
      # rubocop: enable Metrics/CyclomaticComplexity, Metrics/MethodLength
    end
  end
end
