openapi: 3.0.0
info:
  version: "2"
  title: "PactBroker API"
  description: The API for the Pact Broker application
servers:
  - url: "http://{hostname}"
    variables:
      hostname:
        default: "localhost:9292"
        description: "The API instance name."
paths:
  /:
    get:
      description: "Retrieve the index of available resources"
      operationId: indexResource
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
                properties:
                  _links:
                    type: object
                    properties:
                      self:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:publish-pact:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:publish-contracts:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:latest-pact-versions:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:tagged-pact-versions:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:pacticipants:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:pacticipant:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:latest-provider-pacts:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:latest-provider-pacts-with-tag:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:provider-pacts-with-tag:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:provider-pacts:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:latest-version:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:latest-tagged-version:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:webhooks:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:webhook:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:integrations:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:pacticipant-version-tag:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:pacticipant-branch:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:pacticipant-branch-version:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:pacticipant-version:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:metrics:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:can-i-deploy-pacticipant-version-to-tag:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:can-i-deploy-pacticipant-version-to-environment:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:provider-pacts-for-verification:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      beta:provider-pacts-for-verification:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      curies:
                        type: array
                        items:
                          $ref: '#/components/schemas/EmbeddedLinkTemplated'
                      pb:environments:
                        $ref: '#/components/schemas/EmbeddedLink'
                      pb:environment:
                        $ref: '#/components/schemas/EmbeddedLinkTemplated'
  /contracts/publish:
    post:
      description: "Publish consumer contracts with branch, tags and build URL"
      operationId: consumerContractPublish
      requestBody:
        required: true
        description: The consumer contracts, branch, tags and build URL
        content:
          application/json:
            schema:
              type: object
              properties:
                pacticipantName:
                  type: string
                  minLength: 1
                pacticipantVersionNumber:
                  type: string
                  minLength: 1
                tags:
                  type: array
                  nullable: true
                  items:
                      type: string
                branch:
                  type: string
                  nullable: true
                buildUrl:
                  type: string
                  nullable: true
                contracts:
                  type: array
                  items:
                    $ref: '#/components/schemas/ConsumerContractToPublish'
              required:
              - pacticipantName
              - pacticipantVersionNumber
              - contracts
      responses:
        "200":
          description: OK
          content:
            application/hal+json:
              schema:
                type: object
                required:
                  - notices
                properties:
                  notices:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notice'
        "400":
          description: Validation errror
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
            application/hal+json:
              schema:
                type: object
                properties:
                  notices:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notice'

        "409":
          description: Conflict
          content:
            # application/problem+json:
            #   schema:
            #     $ref: '#/components/schemas/ProblemJson'
            application/json:
              schema:
                $ref: '#/components/schemas/PublishConsumerContractConflictResponse'
components:
  parameters:
    PageSize:
      name: page_size
      in: query
      description: The number of results to return per page
      schema:
        type: number
    PageNumber:
      name: page_number
      in: query
      description: The number of the page to return
      schema:
        type: number
  schemas:
    Notice:
      type: object
      required:
        - type
        - text
      properties:
        type:
          type: string
          enum:
            - info
            - debug
            - warning
            - prompt
            - success
            - error
        text:
          type: string

    EmbeddedLink:
      type: object
      required:
      - href
      - title
      properties:
        href:
          type: string
        title:
          type: string
        name:
          type: string
        templated:
          type: boolean

    EmbeddedLinkTemplated:
      allOf:
      - $ref: '#/components/schemas/EmbeddedLink'
      - type: object
        required:
        - templated

    ConsumerContractToPublish:
      type: object
      properties:
        consumerName:
          type: string
          minLength: 1
        providerName:
          type: string
          minLength: 1
        content:
          type: string
          minLength: 1
        contentType:
          enum:
          - application/json
        specification:
          enum:
          - pact
        onConflict:
          default: overwrite
          enum:
          - overwrite
          - merge
      required:
      - consumerName
      - providerName
      - content
      - contentType
      - specification

    PublishConsumerContractConflictResponse:
      description: The custom response when there is a 409 Conflict
      type: object
      properties:
        notices:
          type: array
          items:
            $ref: '#/components/schemas/Notice'
      required:
        - notices

    ProblemJson:
      description: Problem response as per https://www.rfc-editor.org/rfc/rfc9457.html
      type: object
      properties:
        code:
          type: string
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
        status:
          type: integer
        errors:
          type: array
          description: an array of error details to accompany a problem details response
          items:
            type: object
            description: an error object to provide explicit details on a problem towards
              an API consumer
            properties:
              detail:
                type: string
                description: a granular description on the specific error related to a body
                  property, query parameter, path parameters, and/or header
              pointer:
                type: string
                description: a JSON Pointer to a specific request body property that is
                  the source of error
              parameter:
                type: string
                description: the name of the query or path parameter that is the source
                  of error
              header:
                type: string
                description: the name of the header that is the source of error
            required:
            - detail
      required:
      - type
      - title
      - status
